duality-solutions/Dynamic

.github/contributing.md
.github/issue_template.md
.github/pull_request_template.md

Adds annoying contributing, issue and PR templates.

[Doc] Add repo management documents

---

doc/build-windows.md

[Doc] Update Windows Build Documentation

---

src/main.cpp
src/primitives/transaction.h

Remove unneeded checks for supermajority and block version of 1, 2 and 3.
Same as previous release, but will require testing once mining is enabled. Blocks of version 1 will/should be accepted now these checks have been removed.
No. But there would of been one if this wasn't done :)

Remove Checks for Version 1,2,3

---

src/activestormnode.h
src/flat-database.h
src/governance-classes.h
src/governance-exceptions.h
src/governance-misc.h
src/governance-vote.h
src/governance-votedb.h
src/governance.h
src/sandstorm-relay.h
src/sandstorm.h
src/spork.h
src/stormnode-payments.h
src/stormnode-sync.h
src/stormnode.h
src/stormnodeconfig.h
src/stormnodeman.h
src/tinyformat.h
src/torcontrol.h
src/versionbits.h

Sort Headers

---

src/chainparams.cpp

- Fixes the `MineGenesis()` function in chainparams.cpp.  
- New genesis block hash using Argon2d.
Yes, on Ubuntu 16.04 64 bit while mining a new genesis.  Qt wallet runs.

[Chain] Fix miner in chainparams

---

src/main.cpp

I believe this will sort mining out as this was doing checks for DGW and ConvertBitsToDouble
Builds, but requires Greg to confirm with his tests if this indeed fixes the issue of the genesis and subsequent blocks being rejected.
No.

Reformat ContextualCheckBlockHeader

---

src/chainparams.cpp

Changes Parameters for budget block and stormnode testing
Testing in real time.

Changes Parameters for budget block and stormnode testing

---

src/qt/darksilkgui.cpp
src/qt/stormnodelist.cpp

Changes the stormnode tab's default to visible

---

src/governance-classes.cpp
src/governance.cpp
src/governance.h
src/init.cpp
src/qt/darksilk.cpp
src/qt/darksilkgui.cpp
src/qt/darksilkgui.h
src/qt/overviewpage.cpp
src/qt/utilitydialog.cpp
src/qt/utilitydialog.h
src/random.cpp
src/random.h
src/sandstorm.cpp
src/sandstorm.h
src/stormnodeman.cpp
src/wallet/wallet.cpp

Bring Inline with Dash 12.1
Yes locally and have been in discussion about this work direct with Dash devs.
No.

Bring Inline with Dash 12.1

---

src/qt/optionsmodel.cpp

Enable CoinControl by default.
Locally.
No. But will stop us having to tell users how to enable coin control :p

CoinControl On by Default

---

src/chainparams.cpp
src/hash.h
src/miner.cpp

New Argon params; genesis hashes for all three networks, and a small compiler warning fix.
Yes with the Qt wallet miner.

Testing params

---

src/hash.h

accidentally pasted text in hash.h

[Build] Fix build error 

---

src/stormnodeconfig.cpp

Better error message for stormnode config error
Yes, test with Windows 64 bit.
No.

[SN] Better error message for sn config error

---

src/stormnode-payments.cpp
src/stormnode-payments.h
src/stormnode.cpp

Fixes non-functioning stormnodes.
Stormnode is up and running without issue now using Qt wallet on Ubuntu 16.04.1 LTS
#29

[SN] Fixes non-functioning stormnodes

---

src/stormnode-payments.cpp

Improves the debug logging for stormnode payments
Yes

Adds more detailed debug logging for FillBlockPayee()

---

contrib/debian/manpages/darksilkd.1
src/miner.cpp
src/miner.h
src/rpcmining.cpp
src/rpcserver.cpp
src/rpcserver.h

Adds HashMeter.
Tested locally, mined on i7 and hashmeter returns hashes. Cannot confirm if it is accurate, but it is tride and tested code amongst all other coins.
#34

Adds GetHashesPerSec

---

src/governance.h

Increase Proposal Cost to Reduce Spam

---

src/chainparams.cpp

Reduce Retarget Time

---

src/dynode.h

Accidentally removed needed function from governance.h
No need.
No.

Accidental Removal of Function

---

contrib/dynamic-qt.pro
src/qt/optionsmodel.cpp
src/txmempool.h

Correct qt.pro for debugging/future debugging.

qt pro fixes for debug
